package com.example.ui.grocery

import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Add
import androidx.compose.material.icons.filled.Delete
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import com.example.data.local.Customer
import com.example.data.local.Expense
import com.example.data.local.Product
import com.example.ui.OmniViewModel
import java.util.Locale

@Composable fun DashboardScreen(viewModel: OmniViewModel, open: (String) -> Unit) {
    val invoices by viewModel.allInvoices.collectAsState(initial=emptyList()); val customers by viewModel.customers.collectAsState(initial=emptyList()); val products by viewModel.products.collectAsState(initial=emptyList()); val expenses by viewModel.expenses.collectAsState(initial=emptyList())
    val start=java.util.Calendar.getInstance().apply{set(java.util.Calendar.HOUR_OF_DAY,0);set(java.util.Calendar.MINUTE,0);set(java.util.Calendar.SECOND,0);set(java.util.Calendar.MILLISECOND,0)}.timeInMillis
    Column(Modifier.fillMaxSize().padding(16.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){Text("لوحة التحكم",style=MaterialTheme.typography.headlineMedium);Text("إدارة المبيعات والحسابات والمخزون من مكان واحد");Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(8.dp)){StatCard("مبيعات اليوم",money(invoices.filter{it.date>=start}.sumOf{it.totalAmount}),Modifier.weight(1f));StatCard("مصروفات اليوم",money(expenses.filter{it.date>=start}.sumOf{it.amount}),Modifier.weight(1f))};Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(8.dp)){StatCard("الفواتير",invoices.size.toString(),Modifier.weight(1f));StatCard("العملاء",customers.size.toString(),Modifier.weight(1f));StatCard("الأصناف",products.size.toString(),Modifier.weight(1f))};Button({open("add_invoice")},Modifier.fillMaxWidth()){Icon(Icons.Default.Add,null);Spacer(Modifier.width(6.dp));Text("فاتورة مبيعات جديدة")};OutlinedButton({open("customers")},Modifier.fillMaxWidth()){Text("العملاء والحسابات")};OutlinedButton({open("products")},Modifier.fillMaxWidth()){Text("الأصناف والمخزون")};OutlinedButton({open("reports")},Modifier.fillMaxWidth()){Text("التقارير والمصروفات")}}
}
@Composable private fun StatCard(title:String,value:String,modifier:Modifier){Card(modifier){Column(Modifier.padding(12.dp)){Text(title,style=MaterialTheme.typography.labelMedium);Text(value,style=MaterialTheme.typography.titleLarge)}}}

@Composable fun CustomersScreen(viewModel:OmniViewModel, onCustomerClick:(Customer)->Unit={}){val customers by viewModel.customers.collectAsState(initial=emptyList());var add by remember{mutableStateOf(false)};var name by remember{mutableStateOf("")};var phone by remember{mutableStateOf("")};var opening by remember{mutableStateOf("")};Column(Modifier.fillMaxSize().padding(16.dp)){Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically){Text("العملاء والحسابات",style=MaterialTheme.typography.headlineSmall,modifier=Modifier.weight(1f));IconButton({add=true}){Icon(Icons.Default.Add,null)}};if(customers.isEmpty())Box(Modifier.fillMaxSize(),Alignment.Center){Text("لا يوجد عملاء بعد")}else LazyColumn{items(customers,key={it.id}){c->Card(Modifier.fillMaxWidth().padding(vertical=4.dp).clickable{onCustomerClick(c)}){Row(Modifier.padding(14.dp),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(c.name,style=MaterialTheme.typography.titleMedium);if(c.phone.isNotBlank())Text(c.phone);Text("الرصيد الافتتاحي: ${money(c.openingBalance)}")};IconButton({viewModel.deleteCustomer(c)}){Icon(Icons.Default.Delete,"حذف")}}}}}}};if(add)AlertDialog(onDismissRequest={add=false},title={Text("إضافة عميل")},text={Column{OutlinedTextField(name,{name=it},label={Text("اسم العميل")});OutlinedTextField(phone,{phone=it},label={Text("الجوال")});OutlinedTextField(opening,{opening=it},label={Text("الرصيد الافتتاحي")})}},confirmButton={Button({if(name.isNotBlank()){viewModel.saveCustomer(Customer(name=name.trim(),phone=phone.trim(),openingBalance=opening.toDoubleOrNull()?:0.0));name="";phone="";opening="";add=false}}){Text("حفظ")}},dismissButton={TextButton({add=false}){Text("إلغاء")}})}

@Composable fun ProductsScreen(viewModel:OmniViewModel){val products by viewModel.products.collectAsState(initial=emptyList());var add by remember{mutableStateOf(false)};var name by remember{mutableStateOf("")};var sale by remember{mutableStateOf("")};var purchase by remember{mutableStateOf("")};var stock by remember{mutableStateOf("")};var min by remember{mutableStateOf("")};Column(Modifier.fillMaxSize().padding(16.dp)){Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically){Text("الأصناف والمخزون",style=MaterialTheme.typography.headlineSmall,modifier=Modifier.weight(1f));IconButton({add=true}){Icon(Icons.Default.Add,null)}};LazyColumn{items(products,key={it.id}){p->Card(Modifier.fillMaxWidth().padding(vertical=4.dp)){Row(Modifier.padding(14.dp),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(p.name,style=MaterialTheme.typography.titleMedium);Text("بيع: ${money(p.salePrice)} • شراء: ${money(p.purchasePrice)}");Text("المخزون: ${p.stock} ${p.unit}");if(p.stock<=p.minimumStock)Text("تنبيه: المخزون منخفض",color=MaterialTheme.colorScheme.error)};IconButton({viewModel.deleteProduct(p)}){Icon(Icons.Default.Delete,"حذف")}}}}}};if(add)AlertDialog(onDismissRequest={add=false},title={Text("إضافة صنف")},text={Column{OutlinedTextField(name,{name=it},label={Text("اسم الصنف")});OutlinedTextField(sale,{sale=it},label={Text("سعر البيع")});OutlinedTextField(purchase,{purchase=it},label={Text("سعر الشراء")});OutlinedTextField(stock,{stock=it},label={Text("الكمية")});OutlinedTextField(min,{min=it},label={Text("حد التنبيه")})}},confirmButton={Button({if(name.isNotBlank()){viewModel.saveProduct(Product(name=name.trim(),salePrice=sale.toDoubleOrNull()?:0.0,purchasePrice=purchase.toDoubleOrNull()?:0.0,stock=stock.toDoubleOrNull()?:0.0,minimumStock=min.toDoubleOrNull()?:0.0));name="";add=false}}){Text("حفظ")}},dismissButton={TextButton({add=false}){Text("إلغاء")}})}

@Composable fun ReportsScreen(viewModel:OmniViewModel){val invoices by viewModel.allInvoices.collectAsState(initial=emptyList());val expenses by viewModel.expenses.collectAsState(initial=emptyList());var add by remember{mutableStateOf(false)};var title by remember{mutableStateOf("")};var amount by remember{mutableStateOf("")};val sales=invoices.sumOf{it.totalAmount};val paid=invoices.sumOf{it.paidAmount};val exp=expenses.sumOf{it.amount};Column(Modifier.fillMaxSize().padding(16.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){Text("التقارير",style=MaterialTheme.typography.headlineMedium);ReportRow("إجمالي المبيعات",sales);ReportRow("المدفوع",paid);ReportRow("المتبقي",sales-paid);ReportRow("المصروفات",exp);Button({add=true},Modifier.fillMaxWidth()){Text("إضافة مصروف")};Text("عدد الفواتير: ${invoices.size}");Text("صافي الحركة: ${money(sales-exp)}",style=MaterialTheme.typography.titleLarge)};if(add)AlertDialog(onDismissRequest={add=false},title={Text("إضافة مصروف")},text={Column{OutlinedTextField(title,{title=it},label={Text("البيان")});OutlinedTextField(amount,{amount=it},label={Text("المبلغ")})}},confirmButton={Button({if(title.isNotBlank()){viewModel.saveExpense(Expense(title=title.trim(),amount=amount.toDoubleOrNull()?:0.0));title="";amount="";add=false}}){Text("حفظ")}},dismissButton={TextButton({add=false}){Text("إلغاء")}})}
@Composable private fun ReportRow(label:String,value:Double){Card(Modifier.fillMaxWidth()){Row(Modifier.fillMaxWidth().padding(14.dp)){Text(label,Modifier.weight(1f));Text(money(value),style=MaterialTheme.typography.titleMedium)}}}
private fun money(v:Double)=String.format(Locale.getDefault(),"%.2f",v)
